package com.marfeel.compass.tracker

import android.content.Context
import android.net.Uri
import android.view.ViewGroup
import android.widget.FrameLayout
import android.widget.ScrollView
import androidx.core.view.ScrollingView
import androidx.recyclerview.widget.RecyclerView
import com.marfeel.compass.core.model.compass.*
import com.marfeel.compass.core.model.compass.Page
import com.marfeel.compass.core.model.compass.androidCorePageTypes
import com.marfeel.compass.core.model.compass.androidPageType
import com.marfeel.compass.core.ping.IngestPingEmitter
import com.marfeel.compass.di.CompassComponent
import com.marfeel.compass.storage.SessionStorage
import com.marfeel.compass.storage.Storage
import com.marfeel.compass.tracker.multimedia.MultimediaTracking
import com.marfeel.compass.usecase.GetRFV
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch

internal const val compassNotInitializedErrorMessage =
    "Compass not initialized. Make sure CompassTracking::initialize has been called"

internal const val bannedPageTechnologyValue =
    "Page technology value should be greater than 100"

/**
 * CompassTracking is the entry point for all interactions with the library.
 * To access to CompassTracking just retrieve its singleton instance by calling [CompassTracking.getInstance].
 *
 */
interface CompassTracking {
    /**
     * @see trackNewPage(String)
     */
    @Deprecated("Use trackNewPage(url) method", replaceWith = ReplaceWith("trackNewPage(url)"))
    fun startPageView(url: String)

    /**
     * @see trackNewPage(String, ScrollView)
     */
    @Deprecated("Use trackNewPage(url, scrollView) method", replaceWith = ReplaceWith("trackNewPage(url, scrollView)"))
    fun startPageView(url: String, scrollView: ScrollView)

    /**
     * @see trackNewPage(String, ScrollView)
     */
    @Deprecated("Use trackNewPage(url, scrollView) method", replaceWith = ReplaceWith("trackNewPage(url, scrollView)"))
    fun startPageView(url: String, scrollView: RecyclerView)

    /**
     * @see trackNewPage(String, ScrollView)
     */
    @Deprecated("Use trackNewPage(url, scrollView) method", replaceWith = ReplaceWith("trackNewPage(url, scrollView)"))
    fun<T> startPageView(url: String, scrollView: T) where T: FrameLayout, T: ScrollingView


    /**
     * Starts to track the time a user remains on the page given by the [url] parameter as well as the scroll percentage of the content.
     *
     * @param url the url of the page being tracked.
     * @param scrollView view showing the url content.
     * @param rs recirculation source
     */
    fun trackNewPage(url: String, scrollView: ScrollView, rs: String? = null)

    /**
     * @see trackNewPage(String, ScrollView)
     */
    fun trackNewPage(url: String, scrollView: RecyclerView, rs: String? = null)

    /**
     * @see trackNewPage(String, ScrollView)
     */
    fun<T> trackNewPage(url: String, scrollView: T, rs: String? = null) where T: FrameLayout, T: ScrollingView

    /**
     * Starts to track the time a user remains on a page given by the [url] parameter.
     *
     * @param url the url of the page being tracked.
     * @param rs recirculation source
     */
    fun trackNewPage(url: String, rs: String? = null)

    /**
     * Starts to track the time a user remains on the page given by the [screen] parameter as well as the scroll percentage of the content.
     *
     * @param screen the name of the screen being tracked.
     * @param scrollView view showing the screen content.
     * @param rs recirculation source
     */
    fun trackScreen(screen: String, scrollView: ScrollView, rs: String? = null)

    /**
     * @see trackScreen(String, ScrollView)
     */
    fun trackScreen(screen: String, scrollView: RecyclerView, rs: String? = null)

    /**
     * @see trackScreen(String, ScrollView)
     */
    fun<T> trackScreen(screen: String, scrollView: T, rs: String? = null) where T: FrameLayout, T: ScrollingView

    /**
     * Starts to track the time a user remains on a page given by the [screen] parameter.
     *
     * @param screen the name of the screen being tracked.
     */
    fun trackScreen(screen: String, rs: String? = null)

    /**
     * Stops the tracking.
     */
    fun stopTracking()

    /**
     * Associates the user of the application with the records generated by Compass.
     * @param userId the user's identifier in your platform
     */
    @Deprecated("Use setSiteUserId(userID) method", replaceWith = ReplaceWith("setSiteUserId(userId)"))
    fun setUserId(userId: String)

    /**
     * Gets the internal userId used by marfeel for representing uniquely the user
     */
    fun getUserId(): String

    /**
     * Associates the user of the application with the records generated by Compass.
     * @param userId the user's identifier in your platform
     */
    fun setSiteUserId(userId: String)

    /**
     * Sets the user type.
     * @param userType The user type.
     */
    fun setUserType(userType: UserType)

    /**
     * Gets the RFV code from Compass.
     *
     * This function should not be called from the main thread, **if it is called from the main thread, an exception is thrown**.
     */
    fun getRFV(): String?

    /**
     * Gets the RFV code from Compass asynchronously.
     *
     * @param onResult the callback function to handle te result.
     */
    fun getRFV(onResult: (String?) -> Unit)

    fun trackConversion(conversion: String)

    fun trackConversion(conversion: String, options: ConversionOptions)

    /**
     * Sets variables for the current page view.
     *
     * @param name variable name
     * @param value variable value
     */
    fun setPageVar(name: String, value: String)

    /**
     * Sets metrics for the current page view.
     *
     * @param name variable name
     * @param value variable value
     */
    fun setPageMetric(name: String, value: Int)

    /**
     * Sets variables for the current session.
     *
     * @param name variable name
     * @param value variable value
     */
    fun setSessionVar(name: String, value: String)

    /**
     * Sets persistent variables for the user.
     *
     * @param name variable name
     * @param value variable value
     */
    fun setUserVar(name: String, value: String)

    /**
     * Adds persistent user segment for the user.
     *
     * @param name user segment name
     */
    fun addUserSegment(name: String)

    /**
     * Sets persistent user segments for the user, overriding previous ones.
     *
     * @param segments user segments names
     */
    fun setUserSegments(segments: List<String>)

    /**
     * removes user segment for the user.
     *
     * @param name user segment name
     */
    fun removeUserSegment(name: String)

    /**
     * Clears all user segments for the user.
     */
    fun clearUserSegments()

    /**
     * Sets user consent value.
     * @param hasConsent user consent
     */
    fun setUserConsent(hasConsent: Boolean)

    /**
     * Defines landing page por the whole session.
     *
     * @param landingPage landingPage url or screen name.
     */
    fun setLandingPage(landingPage: String)

    /**
     * Manually updates the scroll percentage for the current page.
     *
     * Use this when the scroll view is not a native Android view (e.g. Flutter, Compose).
     * The value is only updated if it exceeds the previously recorded maximum.
     *
     * @param scrollPosition scroll percentage (0-100).
     */
    fun updateScrollPercentage(scrollPosition: Int)

    companion object {
        /**
         * Prepare the Compass SDK to track the pages.
         *
         * Typically, you should initialize the Compass SDK from your Application class.
         * @param context The Android Context.
         * @param accountId Compass account id.
         * @param tech PageTechnology. Only values greater than 100 or 4 or 11, which represents android, are accepted.
         */
        fun initialize(context: Context, accountId: String, tech: Int = androidPageType) {
            require(tech > 100 || androidCorePageTypes.contains(tech)) { bannedPageTechnologyValue }

            CompassComponent.context = context.applicationContext
            if (!CompassTracker.initialized) {
                CompassTracker.initialize(accountId, tech)
            }
        }

        /**
         *
         * @return The singleton instance of the CompassTracking interface
         */
        fun getInstance(): CompassTracking = CompassTracker

        /**
         *
         * @return If compass instance has been initialized properly or not
         */
        internal val initialized: Boolean
            get() = CompassTracker.initialized
    }
}

internal object CompassTracker : CompassTracking {

    private val pingEmitter: IngestPingEmitter by lazy { CompassComponent.ingestPingEmitter }
    private val storage: Storage by lazy { CompassComponent.storage }
    private val sessionStorage: SessionStorage by lazy { CompassComponent.sessionStorage }
    private val getRFV: GetRFV by lazy { CompassComponent.getRFV() }
    private val coroutineScope = CoroutineScope(Dispatchers.IO)


    internal val initialized: Boolean
        get() = sessionStorage.readAccountId() != null

    internal fun initialize(accountId: String, tech: Int) {
        sessionStorage.updateAccountId(accountId)
        sessionStorage.setPageTechnology(tech)
        configureSession()
        pingEmitter.onResumeCallback = ::configureSession
    }

    private fun configureSession() {
        val lastPing = storage.readLastPingTimeStamp()
        if (lastPing == null) {
            val session = storage.readSession()
            if (session == null || session.timeStamp < thirtyMinsAgoInSeconds()) {
                sessionStorage.updateSession()
            }
        } else if (lastPing < thirtyMinsAgoInSeconds()) {
            sessionStorage.updateSession()
        }
    }

    @Deprecated("Use trackNewPage(url) method", replaceWith = ReplaceWith("trackNewPage(url)"))
    override fun startPageView(url: String) {
        trackNewPage(url)
    }

    override fun trackNewPage(url: String, rs: String?) {
        check(initialized) { compassNotInitializedErrorMessage }

        val page = Page(url)
        sessionStorage.updatePage(page)
        sessionStorage.clearPageVars()
        sessionStorage.clearPageMetrics()
        sessionStorage.updateRecirculationSource(rs)
        pingEmitter.start(url, page.pageId, sessionStorage.readSession().id)
        MultimediaTracking.reset()
    }

    @Deprecated("Use trackNewPage(url, scrollView) method", replaceWith = ReplaceWith("trackNewPage(url, scrollView)"))
    override fun<T> startPageView(url: String, scrollView: T) where T: FrameLayout, T: ScrollingView {
        trackNewPage(url, scrollView)
    }

    @Deprecated("Use trackNewPage(url, scrollView) method", replaceWith = ReplaceWith("trackNewPage(url, scrollView)"))
    override fun startPageView(url: String, scrollView: ScrollView) {
        trackNewPage(url, scrollView)
    }

    @Deprecated("Use trackNewPage(url, scrollView) method", replaceWith = ReplaceWith("trackNewPage(url, scrollView)"))
    override fun startPageView(url: String, scrollView: RecyclerView) {
        trackNewPage(url, scrollView)
    }

    override fun<T> trackNewPage(url: String, scrollView: T, rs: String?) where T: FrameLayout, T: ScrollingView {
        trackFrameLayoutPageView(url, scrollView, rs)
    }

    override fun trackNewPage(url: String, scrollView: ScrollView, rs: String?) {
        trackFrameLayoutPageView(url, scrollView, rs)
    }

    private fun<T> trackFrameLayoutPageView(url: String, scrollView: T, rs: String? = null) where T: FrameLayout {
        trackNewPage(url, scrollView, fun(view: T, scroll: Int, _: Int): Double {
            val scrollViewHeight = (view.getChildAt(0).bottom - scrollView.height).toDouble()

            return scroll.toDouble() / scrollViewHeight * 100
        }, rs)
    }

    override fun trackNewPage(url: String, scrollView: RecyclerView, rs: String?) {
        var currentScroll = 0

        trackNewPage(url, scrollView, fun(view: RecyclerView, scroll: Int, oldScroll: Int): Double {
                val scrollViewHeight =
                    (view.computeVerticalScrollRange() - view.computeVerticalScrollExtent()).toDouble()
                val dScroll = scroll - oldScroll
                currentScroll += dScroll

                return currentScroll / scrollViewHeight * 100
            }, rs
        )
    }

    private fun<T> trackNewPage(
        url: String,
        scrollView: T,
        scrollMeasurer: (view: T, scrollY: Int, oldScrollY: Int) -> Double,
        rs: String? = null)
    where T: ViewGroup {
        check(initialized) { compassNotInitializedErrorMessage }
        scrollView.setOnScrollChangeListener { view, _, scrollY, _, oldScrollY ->
            view?.let {
                @Suppress("UNCHECKED_CAST")
                val scrollPosition =
                    scrollMeasurer(view as T, scrollY, oldScrollY).toScrollPercentage()

                pingEmitter.updateScrollPercentage(scrollPosition)
            }
        }

        trackNewPage(url, rs)
    }

    private fun screenUrl(screen: String): String {
        return "https://marfeelwhois.mrf.io/dynamic/${sessionStorage.readAccountId()}/${Uri.encode(screen)}"
    }

    override fun trackScreen(screen: String, rs: String?) {
        trackNewPage(screenUrl(screen), rs)
    }

    override fun<T> trackScreen(screen: String, scrollView: T, rs: String?) where T: FrameLayout, T: ScrollingView {
        trackNewPage(screenUrl(screen), scrollView, rs)
    }

    override fun trackScreen(screen: String, scrollView: ScrollView, rs: String?) {
        trackNewPage(screenUrl(screen), scrollView, rs)
    }

    override fun trackScreen(screen: String, scrollView: RecyclerView, rs: String?) {
        trackNewPage(screenUrl(screen), scrollView, rs)
    }

    internal fun Double.toScrollPercentage(): Int {
        val range = 0..100
        return when {
            this > range.last -> range.last
            else -> this.toInt()
        }
    }

    override fun stopTracking() {
        check(initialized) { compassNotInitializedErrorMessage }
        pingEmitter.stop()
    }

    @Deprecated("Use setSiteUserId(userID) method", replaceWith = ReplaceWith("setSiteUserId(userId)"))
    override fun setUserId(userId: String) {
        setSiteUserId(userId)
    }

    override fun setSiteUserId(userId: String) {
        check(initialized) { compassNotInitializedErrorMessage }
        storage.updateUserId(userId)
    }

    override fun setUserType(userType: UserType) {
        check(initialized) { compassNotInitializedErrorMessage }
        storage.updateUserType(userType)
    }

    override fun updateScrollPercentage(scrollPosition: Int) {
        check(initialized) { compassNotInitializedErrorMessage }
        pingEmitter.updateScrollPercentage(scrollPosition)
    }

    override fun getRFV(): String? =
        getRFV.invoke()?.toString()

    override fun getRFV(onResult: (String?) -> Unit) {
        check(initialized) { compassNotInitializedErrorMessage }
        coroutineScope.launch {
            val response = getRFV()
            onResult(response)
        }
    }

    override fun trackConversion(conversion: String) {
        check(initialized) { compassNotInitializedErrorMessage }
        sessionStorage.addPendingConversion(conversion)
    }

    override fun trackConversion(conversion: String, options: ConversionOptions) {
        check(initialized) { compassNotInitializedErrorMessage }
        sessionStorage.addPendingConversion(conversion, options)
    }

    override fun setPageVar(name: String, value: String) {
        check(initialized) { compassNotInitializedErrorMessage }

        sessionStorage.addPageVar(name, value)
    }

    override fun setPageMetric(name: String, value: Int) {
        check(initialized) { compassNotInitializedErrorMessage }

        sessionStorage.addPageMetric(name, value)
    }

    override fun setSessionVar(name: String, value: String) {
        check(initialized) { compassNotInitializedErrorMessage }

        sessionStorage.addSessionVar(name, value)
    }

    override fun setUserVar(name: String, value: String) {
        check(initialized) { compassNotInitializedErrorMessage }

        storage.setUserVar(name, value)
    }

    override fun addUserSegment(name: String) {
        storage.setUserSegment(name)
    }

    override fun setUserSegments(segments: List<String>) {
        storage.setUserSegment(segments)
    }

    override fun removeUserSegment(name: String) {
        storage.removeUserSegment(name)
    }

    override fun clearUserSegments() {
        storage.clearUserSegments()
    }

    override fun setUserConsent(hasConsent: Boolean) {
        storage.updateUserConsent(hasConsent)
    }

    override fun getUserId(): String {
        return storage.readOriginalUserId()
    }

    override fun setLandingPage(landingPage: String) {
        sessionStorage.setLandingPage(landingPage)
    }
}
